In [5]:
import numpy as np

In [6]:
inputs=[[1,2,3,2.5],[2,5, -1, 2],[ -1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1.0],
         [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]

biases=[2.0,3.0,0.5]

weights2=[[0.1, -0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]]
biases2=[-1.0,2.0,-0.5]



In [7]:
layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2

print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Softmax Activation Function

In [ ]:
import numpy as np
import nnfs
import math

nnfs.init()
#input -> exponentiate -> normalize -> output

layer_outputs=[4.8,1.21,2.385]

exp_values=np.exp(layer_outputs)
norm_values=exp_values / np.sum(exp_values)

print(norm_values)

[0.89528266 0.02470831 0.08000903]


Calculating loss using categorical cross-entropy:

In [1]:
import math

softmax_output=[0.7,0.1,0.2]
target_output=[1,0,0]

loss= -(math.log(softmax_output[0])*target_output[0] +
        math.log(softmax_output[1])*target_output[1]+ 
        math.log(softmax_output[2])*target_output[2])

print(loss)

# Since only the targer index 0 is 1, we can simplify to:
loss= -math.log(softmax_output[0])
print(loss)

0.35667494393873245
0.35667494393873245
